#!/home/ascander/py3/Python-3.3.1/python
# -*- coding: utf-8  -*-

revisados01 = [
]

revisados02 = [
]

revisados03 = [
]

revisados04 = [
]
#1305 últimos de primero
revisados05 = [

 'Liga de la Justicia',
 'Leyenda negra española',
 'Tarzán',
 'Dick Grayson',
 'República Cromañón',
 'María Díaz de Haro (c.1270-1342)',
 'El Tabo',
 'Gobernantes de Argentina',
 'Partido Socialista (Argentina)',
 'Detective Conan',
 'Viswanathan Anand',
 'Monkey D. Luffy',
 'Košice',
 'Laodicea',
 'Club Atlético Universidad Nacional San Agustín',
 'Monasterio de Vallbona de les Monges',
 'Final Fantasy VI',
 'Opportunity',
 'Provincia de El Oro',
 'Galga extensiométrica',
 'Mustafar',
 'Montículo (informática)',
 'Orden del Císter',
 'Linterna Verde',
 'Leslie Cheung',
 'Alto Perú',
 'Sodoma',
 'Política del Sahara Occidental',
 'Frente Revolucionario Antifascista y Patriota',
 'Paintball',
 'Monster (manga)',
 'Invasiones Inglesas',
 'Codificación Huffman',
 'Violadores del Verso',
 'Atizapán de Zaragoza',
 'Foot Ball Club Melgar',
 'Teoría conspirativa',
 'Ren & Stimpy',
 'Universidad de Carabobo',
 'Guerra de Arauco',
 'Chipiona',
 'Monte Plata',
 'María Trinidad Sánchez (provincia)',
 'Hato Mayor',
 'Historia medieval de España',
 'Club Sporting Cristal',
 'Thalía',
 'Injerto',
 'Orihuela',
 'Glenn L. Martin Company',
 'Rodrigo Rato',
 'El lejano país de los estanques',
 'República de Weimar',
 'Paraná (Argentina)',
 'Árbol AVL',
 'Recife',
 'El Chapulín Colorado',
 'Árbol rojo-negro',
 'Árbol binario',
 'Võ Nguyên Giáp',
 'Morcín',
 'Langreo',
 'Cianuro',
 'Curare',
 'Jackie Chan',
 'Historia de Málaga',
 'Nueva Caledonia',
 'Montemayor del Río',
 'Onís',
 'Ailuropoda melanoleuca',
 'Benito Juárez (Distrito Federal)',
 'Vegetación de España',
 'Relación interespecífica',
 'Golpe de Estado',
 'George Stephenson',
 'CBS',
 'Micción',
 'Epífisis',
 'National Broadcasting Company',
 'La princesa Mononoke',
 'Gustavo A. Madero (Distrito Federal)',
 'Pamplona',
 'Harry S. Truman',
 'Aculco',
 'Chimaltenango (departamento)',
 'Música de Argentina',
 'Unión Soviética',
 'Extensión de cuerpos',
 'Pascal (lenguaje de programación)',
 'Tlaxcala',
 'Reino Unido',
 '1982',
 'Karma',
 'Horario de verano en el mundo',
 'Plantae',
 'Magnoliaceae',
 'Linaceae',
 'Xosé Manuel Pereiro',
 'Complejo Industrial La Plata',
 'Jean-Loup Dabadie',
 'Owodog',
 'San Miguel de Horcasitas',
 'Jorge Luis Rojas',
 'Reynosa F.C.',
 'Parque Robert Allerton',
 'Santa María Atarasquillo',
 'Steven Sinofsky',
 'Carranco (San Luis Potosí)',
 'Fe (Los 80)',
 'Cássio Gabus Mendes',
 'Ewen Leslie',
 'Texca',
 'San Pedro las Playas',
 'Takrur',
 'Antje Traue',
 'Solenn Adea Heussaff',
 'WrestleMania 29',
 'Atencingo',
 'Ott Lepland',
 'Andy Milder',
 'Sophie Choudry',
 'Qi Wei',
 'Garett Bischoff',
 'Give Up the Funk (Tear the Roof off the Sucker)',
 'Tony Award por Mejor dirección en obra',
 'Cristian González y Orquesta La Bohemia',
 'Cubitán de Dolores',
 'Coste social',
 'Hoodie Allen',
 'DDR4 SDRAM',
 'Medal of Honor: Frontline',
 'Helga',
 'Sisters of War',
 'Batalla de Monte Tumbledown',
 'Gypsy Heart Tour',
 'Monster in My Pocket',
 'El problema del costo social',
 'Dōjutsu',
 'Elizabeth Eichhorn',
 'Plataforma HD',
 'Suzy (cantante)',
 'Jeremy Scahill',
 'Caxuxi',
 'Marbella Corella',
 'Boris Kodjoe',
 'Carol Cleveland',
 'Joseph Morgan',
 'Aidan Alexander',
 'Sentispac',
 'Nuestra Belleza Latina 2011',
 'Alice: Madness Returns',
 'Exiliado jedi',
 'The Kids Are Alright (película)',
 'Mariscal Francisco Solano López (distrito)',
 'Renato Munster',
 'Revolución egipcia',
 'Royal Pains',
 'Hebe Tien',
 'The weeks Top Charts',
 'My Only Wish',
 'Leandro Sapetti',
 'Živilė Raudonienė',
 'Motorola 68060',
 'Who Are You (canción)',
 'Leonard Mlodinow',
 'Alejandro Urdapilleta',
 'Luciano Abecasis',
 'Luciano Arruga',
 'Xaltianguis',
 'Nuevas series animadas de Hanna-Barbera',
 "Can't Be Tamed",
 'Packed to the Rafters',
 'Christoph Eschenbach',
 "Gyro apó t'óneiro",
 'Mi tío Napoleón',
 'Jodi Gordon',
 'Academia canadiense de Cine y Televisión',
 'Christina Pickles',
 'Auttapon Prakopkong',
 'Tecolutilla',
 'Sociedad Secreta (DC Comics)',
 'Wendy O. Williams',
 'Lisa McCune',
 '3T',
 'Krrish',
 'My Name is Barbra, Two',
 'GMA Network',
 'Veronica Ferres',
 'Stella McCartney',
 'Ampex',
 'Saga Golden Axe',
 'John Debney',
 'La Joya (Morelos)',
 'P. N. Elrod',
 'Carolyn Omine',
 'Cuentos de Eva Luna',
 'Dubai City Tower',
 'Bienvenida Pérez',
 'Antônio Fagundes',
 'Santa María Acuitlapilco',
 'Ángel Quesada',
 'Evolution I (Stargate SG-1)',
 'Homecoming (desambiguación)',
 'San Pedro Buenavista',
 'Los Flippers',
 'León (apellido)',
 'Anchiornis',
 'Internet Protocol Datacast',
 'Oscar Goldman',
 'James Byng',
 'The Saturdays',
 'The Prime Time of Your Life',
 'Alegato antisemita',
 'Lomas de San Juan',
 'La morena',
 'Jeff Conaway',
 'Dunav Kuzmanich',
 'Chris Garver',
 'Julian Iantzi',
 'Thrill Seekers (serie de televisión)',
 'Jesús Morales (actriz)',
 'Felipe Armas',
 'Midtown Madness (videojuego)',
 'Ivanka Trump',
 'Grant Goodeve',
 'Josh Schwartz',
 'Lo siento',
 'Tejido de conducción',
 'Mark Moses',
 'La vida World Tour',
 'El detective cantante',
 'Lucía Palacios',
 'Disney Channel Latinoamérica',
 'Leeland',
 'György Spiró',
 'Bleeding Love',
 'Howard Blake',
 'MADtv',
 'Canal 9 Litoral',
 'Conquista Online',
 'Scansoriopteryx',
 'Carlos Hauptvogel',
 'Adolf Ehrnrooth',
 'Ray Liotta',
 'Selección femenina de fútbol de España',
 'Leandro Rivera',
 'Canal 33 Madrid',
 'Kate Nash',
 'Javier Hernán García',
 'Jeffrey Dean Morgan',
 'El planeta salvaje',
 'Rosa... de lejos',
 'Soukous',
 'Escalerillas',
 'Mujer contra mujer',
 'Frank Serpico',
 'Torres de Malory',
 'Felipe Caicedo',
 'Habbo',
 'Marta Robles',
 'Lea Salonga',
 'Sarah Connor (personaje)',
 'Al Jarreau',
 'Thursday',
 'Distrito de Baños del Inca',
 'El baile en TVN',
 'TVXQ',
 'Dzitbalché',
 'Danny Phantom',
 'Robert Cochran',
 'Joel Surnow',
 'Envy',
 'Will Vinton',
 'Cobra (Manga)',
 'Acció Cultural del País Valencià',
 'Texcoco',
 'Richard Curtis',
 'SECEMIE',
 'Selling England by the Pound',
 'Club Atlético Aguada',
 'Robin Söderling',
 'The Videos 86-98',
 'Mosaico genético',
 'Paul Kagame',
 'Sonic the Hedgehog 3',
 'Rainbow (álbum de Ayumi Hamasaki)',
 'Madness',
 'The Strongest',
 'Emma Bunton',
 'Wolf Vostell',
 'GP2X',
 'Hosni Mubarak',
 'Gabriela Ruffo',
 'Virginia',
 'Caiga quien caiga',
 'Roberto Ayala',
 'Mataró',
 'TV Aichi',
 'Liverpool Football Club',
 'Daniel Bertoni',
 'Ahí está el detalle',
 'Santiago Creel',
 'Mil Mi-24',
 'She-Hulk',
 'Estadio Alberto J. Armando',
 'Selección de fútbol de Panamá',
 'VDSL',
 'Las aventuras de Alicia en el país de las maravillas',
 'Lluvia de animales',
 'Luis Alberto Spinetta',
 'Terrance y Phillip',
 'Club Sportivo Cienciano',
 'Arcadia (desambiguación)',
 'Singleton',
 'Paradoja',
 'Colegio Hogwarts de Magia y Hechicería',
 'Quiz Show: El dilema',
 'Ricardo Lagos',
 'Infierno: Canto Duodécimo',
 'Sony Ericsson c510',
 'Stylo',
 'Isla Pamban',
 'Sergio Zárate',
 'Vaidika Prastisthana Sangha',
 'Lyn Scully',
 'Adiós amor',
 'Crocodile Dundee in Los Angeles',
 'The Piano Lesson',
 'Rap alternativo',
 'National Airlines (Chile)',
 'Sony Ericsson W995',
 'Robert Ortiz',
 'César Montiglio',
 'Louis Chevrolet',
 'Taking Chance',
 'N. N. (serie de televisión)',
 'Leonor Martín',
 'Miguel Moly',
 'Germán Caffa',
 'La Fiamma',
 'Enzo Bearzot',
 'Carlos Guichandut',
 'Slaughterhouse',
 'Vesikko',
 'Family Values Tour 2007',
 'Need for Speed: World',
 'Lucas Rimoldi',
 'Atomizer',
 'Clásica de San Sebastián 2010',
 'Infierno: Canto Vigésimo primero',
 'Mayoi Neko Overrun!',
 'El Generico',
 'Cecilia Rossetto',
 'Pastel de papa',
 'Milan Kalina',
 'Misael Acosta Solís',
 'Citroën Junior Team',
 'Citroën World Rally Team',
 'Ciguapa',
 'Citroën Xsara WRC',
 'Manizales',
 'Entre el amor y el deseo',
 'Nagato (Personaje de Naruto)',
 'Infierno: Canto Vigésimo',
 'Historia de Cuitzeo',
 'Cementerio de Zaragoza',
 'Toti Pasman',
 'SummerSlam (2010)',
 'Ricardo Peralta',
 'Luis Elordi',
 'Happenstance',
 'Reserva de la biosfera Zicuirán Infiernillo',
 'Ángeles Vicente',
 'Luis Alarcón',
 'Danny Casolaro',
 'Club Deportivo Motril Atlético',
 'Corona (heráldica)',
 'La Sombra (luchador)',
 'Bandera de Tlaxcala',
 'Ichiban Ushiro no Dai Maō',
 'Explosiones Nucleares para la Economía Nacional',
 'Iker Cobo',
 'Modelo de escorrentía',
 'Ralph Santolla',
 'Rakuten',
 'Sacrebleu',
 'Demoliendo teles',
 'Habitación 23',
 'William Stanley (inventor)',
 'Tezontle',
 'Lamivudina',
 'Peter Freund',
 'Finales de la NBA de 1962',
 'Medal of Honor (videojuego de 2010)',
 'Keep Bikini Bottom Beautiful',
 'Fernando Bujones',
 'Santuario nacional Pampa Hermosa',
 'Serena Deeb',
 'El Atolón de Funafuti',
 'Los Sims 3',
 'Roderick Strong',
 'Fallout: New Vegas',
 'Estadio Independencia de La Rinconada',
 'The I Heart Revolution: With Hearts as One',
 'The Love of Siam',
 'Intuición femenina',
 'Proceso de Rivonia',
 'The Scythe',
 'Presa de Tucuruí',
 'Condado de Río Blanco',
 'Estación Blas Durañona',
 'Fondo blanco',
 'Condado de Pitkin',
 'Chismes',
 'Alejandro Murature',
 'Antonio Susini',
 'Historia del Club Atlético River Plate',
 'Río Cottica',
 'Estrellas del Porno',
 'City CarShare',
 'Condado de Conejos',
 'Spookyfish',
 'Compuestos orgánicos persistentes',
 'Chocolates Matías López',
 'Moe Letter Blues',
 'Estanques de Milicz',
 'Estación Amalia',
 'La leyenda del beso',
 'Roland Morillot (S613)',
 'Gormiti (serie animada)',
 'The Beautiful People (lucha libre)',
 'Rednecks and Broomsticks',
 'Gothic (serie)',
 'Rock cristiano',
 'Primera B de Chile 2010',
 'Nina Radio Online',
 'Adolfo Ypey',
 'Juan Manuel Insaurralde',
 'Lance Hoyt',
 'Eisblume',
 'Delfín Leguizamón',
 'XENA-AM',
 'Maxence Caron',
 'XEJX-AM',
 'Mighty Mightor',
 'Cloudy with a chance of meatballs',
 'Desgranadora',
 'Chepe Fortuna',
 'Veolia Redbus Urbano',
 'Lectura rápida',
 'Cristóbal de la Mancha y Velazco',
 'Edificio La Inmobiliaria',
 'Alborosie',
 'Neofascismo',
 'Lo esencial de... Alejandro Sanz',
 'Ricardo García Pico',
 'Arquitectura rupestre',
 'She Came In Through the Bathroom Window',
 'Botafogo Futebol Clube',
 'Yoel Hernández',
 'Ética militar',
 'Gasteracantha cancriformis',
 'Exist † trace',
 'Roger Amuruz Gallegos',
 'The Pagemaster',
 'San Salvador el Seco',
 'South Park (videojuego)',
 'Mujeres de arena (telenovela de 1993)',
 'Museo Municipal de Ciencias Naturales y Arqueología de San Antonio',
 'Temperamento (Artista)',
 'X-Time',
 'Jump Square',
 'Iglesia Arciprestal de Santa María del Salvador (Chinchilla de Montearagón)',
 'René Segura',
 'Grand Slam Cup',
 'Iglesia de San Andrés (Valladolid)',
 'Llanura Indo-Gangética',
 'Son Sardina',
 'Transcarga',
 'Carmelo Hurtado',
 'Yautepec de Zaragoza',
 'Esteban Terralla y Landa',
 'Mohamed Rouicha',
 'Almacén 13',
 'Ektor Rivera',
 'Maximiliano Caire',
 'Luis Rivero del Val',
 'Minería ilegal en Perú',
 '21st Century Breakdown (canción)',
 'Jorge Uliarte',
 'Zona Metropolitana de Tuxtla Gutiérrez',
 'Luis Medina Castro',
 'Vuelta a Guatemala',
 'Rostros Ocultos',
 'A Little Less Sixteen Candles, a Little More "Touch Me"',
 'Club Atlético San Fernando',
 'Busseto',
 'Batalla de Las Cangrejeras',
 'Manuel Atanasio Cabañas',
 'Carimagua',
 'Scipione Riva-Rocci',
 'Bukit Timah',
 'Dalmiro Adaro',
 'Uncharted 2: El Reino de los Ladrones',
 'Río Citarum',
 'Las aventuras de Miss Spider',
 'Aída García',
 'Ot Pi',
 'Religión en Melena del Sur',
 'Pseudomyrmex triplarinus',
 'Joaquín Villalón Díez',
 'Krab Borg',
 'Maleficio (novela)',
 'Cheat Engine',
 'Dave Sanders',
 'Shotgun Messiah',
 'Pasión (emoción)',
 'Castella Vetula',
 'Smiley Face (película)',
 'Todd (Beavis and Butthead)',
 'Halloween II (película del 2009)',
 'Cantón Chone',
 'Nuestra Señora de las Nieves (La Palma)',
 'This Is Us Tour',
 'La cúpula (novela)',
 'José María Salvadores',
 'Raoul Bova',
 'Cañón de Saturban',
 'Jah Cure',
 'Nada es color de rosa',
 'Matthew McGrory',
 'Verónica Coronel',
 'Jesús Moreno Rodríguez',
 'Morgan Gould',
 'Esko Aho',
 'Joe Rogan',
 'Rachel Dawes',
 'Scarve',
 'Tess Mercer',
 'The World Ends with You',
 'Sangre de lobos',
 'Salud en México',
 'Enugu',
 'Saber vivir',
 'Mazda 323',
 'Carlos Antonio Vélez',
 'TVMax',
 'HB (banda)',
 'K-Paz de la Sierra',
 'Jason X',
 'Área Metropolitana de Ciudad del Este',
 'Enredados',
 'Oerlikon 20 mm',
 'Río Grande (Oaxaca)',
 'Pretty Guardian Sailor Moon',
 'Sonic Underground',
 'Violetta Villas',
 'Colonia Narvarte',
 "Mexico's Next Top Model",
 'Censura en Cuba',
 'Kronos (banda)',
 'Heros severus',
 'Valero Lecha',
 '90210',
 'Jeton Kelmendi',
 'Jumper (novela)',
 'Command & Conquer 3: La ira de Kane',
 'Beba Bidart',
 'Craig Mabbitt',
 'Amor ciego (película)',
 'Port Royale 2: Imperio y Piratas',
 'Rodrigo Marangoni',
 'Richie Ray',
 'Cinderella III: A Twist in Time',
 'Prosthechea cochleata',
 'Miraflores (Boyacá)',
 'Michèle Bennett',
 'Las aventuras de Rocky y Bullwinkle',
 'Alejandro Morera Soto',
 'Alonso Núñez de Haro',
 'William Edward Forster',
 'La ciudad de los tísicos',
 'Oxtotitlán',
 'Grace (Stargate SG-1)',
 'Orlando Colón',
 'Oteruelo (La Rioja)',
 'Colonia Nápoles',
 'Nuestra Señora de Zapopan',
 'Huracán de tipo Cabo Verde',
 'Hugo Leicht',
 'Causas de la Segunda Guerra Mundial',
 'Adolfo Díaz Recinos',
 'Petra Pau',
 'Radio Panamericana',
 'Voltaire García',
 'Esmeraldas del Caos',
 'Parroquia Urbana Punta Cardón',
 'UCoz',
 'Unfortunate Snort',
 'Celal Bayar',
 'Pinkly Smooth',
 'Santa Cruz Acalpixca',
 'Joakim Soria',
 'Leon Wood',
 'Estación Intermodal Bellavista de La Florida',
 'Río La Pasión',
 'La otra mitad del sol (telenovela colombiana)',
 'Mandy Moore (álbum)',
 'Dragon Quest: Dai no Daibouken',
 'Los viajes de Clovis Dardentor',
 'Yuki Nagato',
 'Movimiento Revolucionario Liberal',
 'Cookin’ Soul',
 'El rostro de Analía',
 'La paisana Jacinta',
 'I Wanna Be With You',
 'Fairchild AC-119',
 'Entre el mar y una estrella',
 'Impel Down',
 'Beto Casella',
 'Najib Tun Razak',
 'Vuélveme a querer',
 'Estudios sociales',
 'Louisa Hanoune',
 'Luigi Galleani',
 'Poneglyph',
 'Resident Evil 2 DualShock Edition',
 'We Made You',
 'Fernando Béjar Durá',
 'Renault R202',
 'Inmigración argentina en España',
 'Inmigración mexicana en Estados Unidos',
 'Kenny Washington',
 'Escuela Industrial Salesiana San Ramón',
 'Fernando Navarro Morán',
 'Saint Seiya Next Dimension',
 'Mimí',
 'Sekirei',
 'Inmigración en Chile',
 'Tableta digitalizadora',
 'Parque nacional natural El Cocuy',
 'Chía (Cundinamarca)',
 'Tuone Udaina',
 'Club de Deportes Puerto Montt',
 'Shihan',
 'Ross Geller',
 'Remo (deporte)',
 'Incubus (banda)',
 'Provincia de Pichincha',
 'Callosa de Segura',
 'Prong',
 'Princesa Daisy',
 'Navegantes del Magallanes',
 'Mort Cinder',
 'Vince Clarke',
 'Quiste ovárico',
 'Liga Deportiva Universitaria de Quito',
 'Johnny Cash',
 'El Alto',
 'Trigun',
 'Nick Fury',
 'Terremoto de México de 1985',
 'Ciudad Bolívar (Bogotá)',
 'Santa Ana Chiautempan',
 'Automodelismo',
 'Portsmouth Football Club',
 'Iker Casillas',
 'Silent Hill',
 'Escuela Militar (estación)',
 'Bestia de Gévaudan',
 'Rafael Pombo',
 'Palamós Club de Futbol',
 'Terran',
 'Kennedy (Bogotá)',
 'Capcom',
 'Monaguillo',
 'Instituto Tecnológico de Ciudad Madero',
 'Unión Balompédica Conquense',
 'AMD Am386',
 'La Robla',
 'Sociedad Deportiva Huesca',
 'Santa Rosa de Calamuchita',
 'Naturalización',
 'TV Brasil',
 'Gillian Anderson',
 'Bowser',
 'Dr. No (película)',
 'Operación Trueno (película)',
 'Club Deportes Concepción',
 'Jet Set Radio',
 'All Grown Up!',
 'Calle 13 Universal',
 'Réquiem',
 'Darth Revan',
 'Jim Root',
 'Tentación (telenovela)',
 'Olombrada',
 'Antonello Venditti',
 'Rino Gaetano',
 'Rol en vivo',
 'Club de Deportes Copiapó',
 'Coquimbo Unido',
 'Seguridad y salud laboral',
 'Xuxa',
 'Mantenimiento de software',
 'Parma Football Club',
 'René Lavand',
 'Flans',
 'César Borgia',
 'Società Sportiva Lazio',
 'Timol',
 'Cine de terror',
 'Majin Boo',
 'Cell (personaje de Dragon Ball)',
 'Desastre',
 'Ivy Queen',
 'Mariano Mores',
 'Cultural y Deportiva Leonesa',
 'Club Deportivo Alcoyano',
 'Defensor Sporting Club',
 'Michael Rasmussen',
 'Andreas Klöden',
 'José Manuel de la Sota',
 'Fuente Álamo de Murcia',
 'Despina Vandi',
 'Club Deportivo Arturo Fernández Vial',
 'Harley Quinn',
 'Club Deportivo Castellón',
 'Riddler',
 'Microsoft Visual Studio',
 'Real Murcia Club de Fútbol',
 'Carlos Anwandter',
 'Monasterio de Montserrat',
 'Fabian Cancellara',
 'Tom Boonen',
 'Ryō Hirohashi',
 'AeroSur',
 'República de Ragusa',
 'Florinda Meza',
 'Partido de Chascomús',
 'Jay Kay',
 'Chiquimula (departamento)',
 'Berri Txarrak',
 'Español centroamericano',
 'Doñinos de Salamanca',
 'Sucre',
 'Virreinato del Perú',
 'Departamento de Tacna',
 'Áster',
 'Che',
 'A sangre fría (película de 1967)',
 'Satanás',
 'Christiaan Neethling Barnard',
 'Aelo',
 'Aguascalientes (Aguascalientes)',
 'Donnie Darko',
 'Juliaca',
 'Sōkaku Takeda',
 'Misery (película)',
 'Aurora de Chile',
 'Candelario',
 'Mu (continente perdido)',
 'Γ',
 'Cartismo',
 'Diego Rivera',
 'Barruecopardo',
 'Wall Street (película)',
 'Full Metal Jacket (película)',
 'Vejer de la Frontera',
 'Grupo Televisa',
 'Eiichirō Oda',
 'Tetraciclina',
 'Religión en España',
 'Tom Berenger',
 'Kendō',
 'Psicosis (película de 1960)',
 'Fantasma',
 'Aeropuerto Internacional Ministro Pistarini',
 'Panthera tigris',
 'Teoría de categorías',
 'Cumbres borrascosas (película de 1939)',
 'Dinero',
 'Detector de mentiras',
 'Sistema de control',
 'Historia de América del Norte',
 'Instituto Tecnológico de Durango',
 'Tikal',
 'Victoria de Durango',
 'Embarazo',
 '534',
 '260',
 'Espacio métrico',
 'Werner Herzog',
 'El Bierzo',
 'BMW',
 'Batalla de Arica',
 'Mitología japonesa',
 'The Cure',
 'Vibrio cholerae',
 'Gaita zuliana',
 'Campylobacter',
 'Aa! Megami-sama',
 'Real Club Deportivo de La Coruña',
 'Historia de Libia',
 'Mole de caderas',
 'Wilfredo Gómez',
 'Historia económica',
 'Cultura de Bolivia',
 'Boro',
 'Panamá (ciudad)',
 'Amala',
 'Texas',
 'Hunter × Hunter',
 'Instalación industrial',
 'Plantago lanceolata',
 'Provincia de Jujuy',
 'Provincia de La Pampa',
 'Provincia de Misiones',
 'Provincia de Santiago del Estero',
 'Provincia de Camaná',
 'Necton',
 'Sherlock Holmes',
 'Portaaviones',
 'César Milstein',
 'Michael Jordan',
 'Huella filogenética',
 'Ghana',
 'Managua',
 'Isla Grande de Tierra del Fuego',
 'Energía solar térmica',
 'Hiragana',
 'ARN no codificante',
 'Antofagasta',
 'Ruby',
 'Terapia génica',
 'Ronald Reagan',
 'Mangaka',
 'Cultura de Colombia',
 'Historia de Honduras',
 'The Silence of the Lambs (película)',
 'Gosu (expresión)',
 'Control de gestión',
 'Contabilidad financiera',
 'Bandera nacional',
 'Política de México',
 'Medicamento',
 'Historia de Panamá',
 'Departamento de Potosí',
 '1992',
 'Ciudad de Salta',
 'Aguascalientes',
 'Prostitución',
 'Morelos',
 '11 de marzo',
 'Thomas Malthus',
 'Topografía',
 'La Rioja (España)',
 'Midget',
 'Cultura de México',
 'Historia de la inteligencia artificial',
 'Cadmio',
 'América del Norte',
 'Colonia Cuauhtémoc',
 'The Twilight Saga: Eclipse',
 'Emanuele Molin',
 'Historia del Atlético Nacional',
 'R. J. Mitchell',
 'Ejército del Pueblo Paraguayo',
 'Lala Satalin Deviluke',
 'Carlos de la Fuente',
 'Club Caza Monstruos',
 'Terry Tyler',
 'Somos tú y yo: un nuevo día',
 'Fairchild C-123 Provider',
 'Destroy All Humans!',
 'Idioma eudeve',
 'Vallnord',
 'FOX (España)',
 'Hayate no Gotoku!',
 'Chino & Nacho',
 'Empire EP',
 'Luis Izquierdo Fredes',
 'FIFA 10',
 'Rozen Maiden',
 'Them Crooked Vultures',
 'Tetraquark',
 'Lo de Carranza',
 'Juan de Limpias Carvajal',
 'Expedición Auxiliar de Santa Cruz a Quito',
 'Pattaya',
 'Raymond Thevenot',
 'Historia del Club de Deportes Cobreloa',
 'Región Sierra Norte',
 'Club Atlético Banfield',
 'Ladyhawke (película)',
 'Diego Valdés',
 'Our Song',
 'Elecciones municipales de Nicaragua de 2009',
 'Fernando Cordero Fonseca',
 'Rosita Pelayo',
 'Basílica de Nuestra Señora del Rosario de Chiquinquirá',
 'Bristol Jupiter',
 'Hilda de Polaris',
 'Fearless (película de 1993)',
 'Ministerio de Comercio, Industria y Turismo de Colombia',
 'Ronnie Aldrich',
 'Eva Cortés',
 'Kid vs. Kat',
 'Sativanorte',
 'Kaija Kärkinen',
 'Daniel Sturridge',
 'Jardín Balbuena',
 'Transporte en la ciudad de Rosario',
 'Capitán McCluskey',
 'Isla Paradise',
 'Phan Thị Kim Phúc',
 'Cementerio de Podunk',
 'Batalla de Tablada',
 'Johan Rodríguez',
 'Los guardianes del tiempo',
 'Instituto Nacional de Migración (México)',
 'Julián Cerdá Vicente',
 'Federación Fajardina',
 'Back-side bus',
 'María Colón de la Cueva',
 'Santuario de fauna y flora Iguaque',
 'Tronic',
 'Mirtha Medina',
 'Diego (álbum de Diego González)',
 'Doña Bella',
 'Crimson (cómic)',
 'Ricky Hatton',
 'Tailandia en la Segunda Guerra Mundial',
 'Blue Gender',
 'Redes inalambricas',
 'Club Atlético Huracán (Moquegua)',
 'Delegacion Benito Juarez',
 'Batalla de Moquegua',
 'Manuel Castañer',
 'Castle',
 'Bakemonogatari',
 'BlueTrack',
 'Partido Socialista de la Revolución Nacional',
 'Sellos de España en 1999',
 'Petróleo',
 'Taken by Cars',
 'Serie Mundial de béisbol de 1996',
 'Disa Records',
 'IPhone 3GS',
 'Germano argentinos',
 'Víllodas',
 'Ricardo Steer',
 'Giro de Italia 2001',
 'Team Argos-Shimano',
 'Krisztián Vadócz',
 'Matthias Rettner',
 'Kick Buttowski: Suburban Daredevil',
 'Tengo todo excepto a ti',
 'Bardaisan',
 'Spin (álbum)',
 'Luke Jacobz',
 'Luis Alberto Pozzi',
 'Zeke & Luther',
 'Ivantosaurus',
 'Ksenia Sujínova',
 'Nowhere Islands',
 'Chris Coghill',
 'Alaa Abdul-Zahra Khashan',
 'Xicohtzinco',
 "Madalyn Murray O'Hair",
 'Montalbán (Carabobo)',
 'Indigo (álbum)',
 'Nohmul',
 'Liga Nacional de Guatemala 1993/94',
 'Edurne Uriarte',
 'Teemu Pukki',
 'Anillo del Pescador',
 'Liga Nacional de Guatemala 1998/99',
 'Tulio Pizzi',
 'José María Morelos',
 'Tauro Sport Auto',
 'Sun Channel',
 'Clase (biología)',
 'Wifredo Espina Claveras',
 'Juan Almeida Bosque',
 'Alexander Corvinus',
 'Jesús Casillas Romero',
 'Botellita de Jerez',
 'Nicolás Romero (coronel)',
 'Festival Cultural de Mayo',
 'Bi Sheng',
 'La otra cara del alma',
 'Gabriela Rivero',
 'Martín Del Pomar',
 'Brendon Urie',
 'Kirt Hector',
 'Carlos Pellegrini',
 'Dominique',
 'José Rosas Moreno',
 'Incendio de la Iglesia de la Compañía',
 'Tuxtla Gutiérrez',
 'Jaques Leclercq',
 'We Butter The Bread With Butter',
 'Tina de Jarque',
 'Rocky Balboa',
 'Joan Fuster Bonnin',
 'Thrust SSC',
 'Manuel Alas Sardaneta y Pompa',
 'María de Cleves',
 'José Saturnino Cardozo',
 'Robin Henderson',
 'The Dr. Oz Show',
 'Francisco Díaz Pimienta',
 'Giezi',
 'Donato Fuejo',
 'Prelatura de Humahuaca',
 'Malcolm X',
 'Quinta de Anauco',
 'Isla Baltra',
 'Agencia EFE',
 'Julio César Aráoz',
 'Maximiliano I de México',
 'Vicepresidente de Venezuela',
 'Javier Alfaya',
 'Sidney Bechet',
]

revisados06 = [
]

revisados07 = [
]

revisados08 = [
]

revisados09 = [
]

revisados10 = [
]

revisados11 = [
]

revisados12 = [
]
revisados = set(revisados01+revisados02+revisados03+revisados04+revisados05+revisados06+revisados07+revisados08+revisados09+revisados10+revisados11+revisados12)
