name: safelanguage
channels:
- defaults
- conda-forge
dependencies:
- python=3.6
- jupyter
- pytest
- scikit-learn
- scipy
- pandas
- pandas-summary
- lxml
- nltk
- datadotworld-py
- pip:
  - environment_kernels
  - missingno
  - wikipedia
